
defaults: &defaults
  adapter: postgres
  encoding: unicode
  pool: 5
  username: USERNAME
  password: PASSWORD

development:
  database: sample_app_development
  host: localhost
  <<: *defaults

test:
  database: sample_app_test
  host: localhost
  <<: *defaults

production:
  database: sample_app_test
  host: localhost
  <<: *defaults
